import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Upload, Sparkles, AlertCircle, CheckCircle2, ChevronRight, ChevronLeft } from 'lucide-react';

interface UploadGameModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess: () => void;
}

const UploadGameModal: React.FC<UploadGameModalProps> = ({ isOpen, onClose, onSuccess }) => {
  const [step, setStep] = useState(1);
  const [isGeneratingAI, setIsGeneratingAI] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  
  const [formData, setFormData] = useState({
    title: '',
    missionBrief: '',
    classification: 'Action',
    buildVersion: '1.0.0'
  });

  const categories = ['Action', 'RPG', 'Strategy', 'Simulation', 'Adventure', 'Horror', 'Sports', 'Puzzle'];

  const handleAICompose = async () => {
    if (!formData.title) return;
    
    setIsGeneratingAI(true);
    // Simulate Gemini AI generation Logic
    // In Phase 5 we will hook this to the real backend Gemini proxy
    try {
      await new Promise(resolve => setTimeout(resolve, 1500));
      setFormData(prev => ({
        ...prev,
        missionBrief: `Generated by ForgeAI for "${formData.title}": An adrenaline-pumping ${formData.classification.toLowerCase()} experience that pushes the boundaries of indie gaming. Navigate complex environments and master unique mechanics! (Hooked to Gemini API in Phase 5)`
      }));
    } finally {
      setIsGeneratingAI(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);
    
    try {
      const token = localStorage.getItem('token');
      const response = await fetch(`${import.meta.env.VITE_API_URL}/api/games/upload`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify(formData)
      });
      
      if (response.ok) {
        onSuccess();
        onClose();
        setStep(1);
        setFormData({ title: '', missionBrief: '', classification: 'Action', buildVersion: '1.0.0' });
      }
    } catch (error) {
      console.error('Upload failed:', error);
    } finally {
      setIsSubmitting(false);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
      <motion.div 
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        onClick={onClose}
        className="absolute inset-0 bg-black/80 backdrop-blur-md"
      />
      
      <motion.div
        initial={{ opacity: 0, scale: 0.9, y: 20 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.9, y: 20 }}
        className="relative w-full max-w-2xl bg-[#121214] border border-white/10 rounded-3xl overflow-hidden shadow-2xl"
      >
        {/* Header */}
        <div className="p-6 border-b border-white/5 flex items-center justify-between">
          <div>
            <h2 className="text-2xl font-bold text-white">Publish New Mission</h2>
            <p className="text-gray-500 text-sm">Step {step} of 2</p>
          </div>
          <button onClick={onClose} className="p-2 hover:bg-white/5 rounded-full transition-colors text-gray-400">
            <X size={20} />
          </button>
        </div>

        <div className="p-8">
          <form onSubmit={handleSubmit}>
            <AnimatePresence mode="wait">
              {step === 1 ? (
                <motion.div
                  key="step1"
                  initial={{ opacity: 0, x: 20 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: -20 }}
                  className="space-y-6"
                >
                  <div className="space-y-2">
                    <label className="text-sm font-medium text-gray-400">Mission Title</label>
                    <input 
                      required
                      value={formData.title}
                      onChange={e => setFormData({...formData, title: e.target.value})}
                      placeholder="e.g. Neon Horizon"
                      className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-3 text-white focus:outline-none focus:border-blue-500/50 transition-all"
                    />
                  </div>

                  <div className="space-y-2">
                    <div className="flex items-center justify-between">
                      <label className="text-sm font-medium text-gray-400">Mission Brief (Description)</label>
                      <button 
                        type="button"
                        onClick={handleAICompose}
                        disabled={!formData.title || isGeneratingAI}
                        className="flex items-center gap-1.5 text-xs font-semibold text-purple-400 hover:text-purple-300 disabled:opacity-50 transition-all"
                      >
                        {isGeneratingAI ? (
                          <div className="animate-spin h-3 w-3 border-t-2 border-purple-400 rounded-full" />
                        ) : (
                          <Sparkles size={14} />
                        )}
                        Compose with ForgeAI
                      </button>
                    </div>
                    <textarea 
                      required
                      value={formData.missionBrief}
                      onChange={e => setFormData({...formData, missionBrief: e.target.value})}
                      placeholder="Describe your game's universe..."
                      rows={4}
                      className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-3 text-white focus:outline-none focus:border-blue-500/50 transition-all resize-none"
                    />
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <label className="text-sm font-medium text-gray-400">Classification</label>
                      <select 
                        value={formData.classification}
                        onChange={e => setFormData({...formData, classification: e.target.value})}
                        className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-3 text-white focus:outline-none focus:border-blue-500/50 transition-all appearance-none cursor-pointer"
                      >
                        {categories.map(c => <option key={c} value={c}>{c}</option>)}
                      </select>
                    </div>
                    <div className="space-y-2">
                      <label className="text-sm font-medium text-gray-400">Tactical Version</label>
                      <input 
                        value={formData.buildVersion}
                        onChange={e => setFormData({...formData, buildVersion: e.target.value})}
                        className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-3 text-white focus:outline-none focus:border-blue-500/50 transition-all"
                      />
                    </div>
                  </div>
                </motion.div>
              ) : (
                <motion.div
                  key="step2"
                  initial={{ opacity: 0, x: 20 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: -20 }}
                  className="space-y-8"
                >
                  <div className="border-2 border-dashed border-white/10 rounded-3xl p-12 text-center group hover:border-blue-500/30 transition-all cursor-pointer bg-blue-500/0 hover:bg-blue-500/5">
                    <div className="flex flex-col items-center gap-4">
                      <div className="p-4 bg-zinc-800 rounded-2xl text-gray-400 group-hover:text-blue-400 transition-colors">
                        <Upload size={32} />
                      </div>
                      <div>
                        <p className="text-white font-semibold">Drop your game build here</p>
                        <p className="text-gray-500 text-sm mt-1">Accepts .zip or .rar (Max 500MB)</p>
                      </div>
                    </div>
                  </div>

                  <div className="bg-blue-500/5 border border-blue-500/10 rounded-2xl p-4 flex gap-3">
                    <CheckCircle2 className="text-blue-400 flex-shrink-0" size={18} />
                    <p className="text-xs text-blue-200/80 leading-relaxed">
                      Forge infrastructure automatically generates an optimized CDN link and issues a Let's Encrypt certificate for your deployment.
                    </p>
                  </div>
                </motion.div>
              )}
            </AnimatePresence>

            {/* Footer Buttons */}
            <div className="mt-10 flex items-center justify-between">
              {step === 1 ? (
                <div />
              ) : (
                <button 
                  type="button"
                  onClick={() => setStep(1)}
                  className="flex items-center gap-2 text-gray-400 hover:text-white transition-colors font-medium"
                >
                  <ChevronLeft size={18} />
                  Back
                </button>
              )}

              {step === 1 ? (
                <button 
                  type="button"
                  onClick={() => setStep(2)}
                  className="bg-zinc-800 hover:bg-zinc-700 text-white px-8 py-3 rounded-xl font-semibold transition-all flex items-center gap-2"
                >
                  Next Tier
                  <ChevronRight size={18} />
                </button>
              ) : (
                <button 
                  type="submit"
                  disabled={isSubmitting}
                  className="bg-blue-600 hover:bg-blue-500 text-white px-10 py-3 rounded-xl font-semibold transition-all disabled:opacity-50"
                >
                  {isSubmitting ? 'Syncing...' : 'Initiate Deployment'}
                </button>
              )}
            </div>
          </form>
        </div>
      </motion.div>
    </div>
  );
};

export default UploadGameModal;
